apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lmeun3wzj-go
  janus-idp.io/tekton: lmeun3wzj-go
  backstage.io/kubernetes-id: lmeun3wzj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lmeun3wzj-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
